baseurl = "http://guptayuvraj.github.io"
languageCode = "en-us"
title = "Blog"
theme = "greyshade"

[author]
name = "Yuvraj Gupta"
email = "gupta.yuvraj@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"

[Params]
author = "Yuvraj Gupta"
subscribe_email = "gupta.yuvraj@gmail.com"

facebook_user = "gupta.yuvraj"
twitter_user = "yuvrajgupta14"
github_user = "guptayuvraj"
stackoverflow_user = "yuvraj-gupta"
stackoverflow_user_id = "3678433"
linkedin_user = "guptayuvraj"
quora_user = "Yuvraj-Gupta-1"

facebook_like = true
twitter_tweet_button = true
google_plus_one = "true"
addthis_profile_id = "true"

disqus_short_name = "yuvrajgupta"
disqus_show_comment_count = true

google_analytics_tracking_id = "UA-75311692-1"
